import { launch, boot } from './rec.mjs';
const S = '/private/tmp/claude-501/-Users-mg-dev-fablesynth/fa60d6d2-e623-4a7c-8473-ddc564ff37cf/scratchpad';
const { browser, page } = await launch();
await boot(page, 'seq');
await page.evaluate(() => document.querySelector('button[aria-label="Close tour"]')?.click());
await page.evaluate(() => { const sel = document.querySelector('header select'); sel.value = '41'; sel.dispatchEvent(new Event('change', { bubbles: true })); });
await page.waitForTimeout(1200);
await page.evaluate(() => document.querySelector('button[aria-label="Start sequencer"]')?.click());
await page.waitForTimeout(2500);
await page.evaluate(() => window.__fableSq.store.getState().enterFocus(2));
await page.waitForTimeout(1000);
await page.evaluate(() => [...document.querySelectorAll('button')].find((b) => b.textContent.trim() === 'EDIT')?.click());
await page.waitForTimeout(800);
await page.evaluate(() => document.querySelector('.sq-auto-add')?.click());
await page.waitForTimeout(800);
console.log(await page.evaluate(() => [...document.querySelectorAll('.sq-auto, .sq-auto svg[role=img], .panel-filter [aria-label="CUTOFF"]')].map((e) => { const b = e.getBoundingClientRect(); return `${e.tagName} ${e.getAttribute('aria-label') ?? ''} ${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)}`; }).join('\n')));
console.log('scrollH', await page.evaluate(() => [document.documentElement.scrollHeight, document.querySelector('.sq-device, .sq-focus, main')?.scrollHeight]));
await page.screenshot({ path: `${S}/sq-edit-echo.png`, scale: 'css' });
await browser.close();
