import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--autoplay-policy=no-user-gesture-required', '--mute-audio', '--force-device-scale-factor=2'] });
const ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto('http://localhost:5199/bass/');
await page.waitForTimeout(1000);
await page.evaluate(() => document.getElementById('power-on')?.click());
await page.waitForTimeout(2000);
const cdp = await ctx.newCDPSession(page);
let n = 0, size = '';
cdp.on('Page.screencastFrame', (f) => { n++; size = `${f.metadata.deviceWidth}x${f.metadata.deviceHeight} pageScale=${f.metadata.pageScaleFactor}`; cdp.send('Page.screencastFrameAck', { sessionId: f.sessionId }); if (n === 5) globalThis.d = f.data; });
await cdp.send('Page.startScreencast', { format: 'jpeg', quality: 88, maxWidth: 3840, maxHeight: 2160 });
await page.evaluate(() => window.__fableBl.store.getState().play());
await page.waitForTimeout(3000);
await cdp.send('Page.stopScreencast');
const buf = Buffer.from(globalThis.d, 'base64');
(await import('node:fs')).writeFileSync('/private/tmp/claude-501/-Users-mg-dev-fablesynth/fa60d6d2-e623-4a7c-8473-ddc564ff37cf/scratchpad/zt.jpg', buf);
console.log('frames/3s', n, size);
await browser.close();
