// DO NOT EDIT — generated by scripts/build-drum-samples.mjs
import sample0Url from '../../../assets/drum-samples/808/808SD_SD5050.WAV?url';
import sample1Url from '../../../assets/drum-samples/808/808CP_CP.WAV?url';
import sample2Url from '../../../assets/drum-samples/808/808CH_CH.WAV?url';
import sample3Url from '../../../assets/drum-samples/808/808OH_OH50.WAV?url';
import sample4Url from '../../../assets/drum-samples/808/808CY_CY5050.WAV?url';

export interface DrumOneShot { name: string; sampleRate: number; data: Float32Array }

const RAW = [
  { name: '808SD', url: sample0Url },
  { name: '808CP', url: sample1Url },
  { name: '808CH', url: sample2Url },
  { name: '808OH', url: sample3Url },
  { name: '808CY', url: sample4Url },
] as const;

function decodeWavPcm16(buf: ArrayBuffer): { sampleRate: number; data: Float32Array } {
  const u8 = new Uint8Array(buf); const dv = new DataView(buf);
  const tag = (at: number) => String.fromCharCode(u8[at], u8[at + 1], u8[at + 2], u8[at + 3]);
  let sampleRate = 0, dataAt = -1, dataBytes = 0;
  for (let at = 12; at + 8 <= u8.length;) {
    const size = dv.getUint32(at + 4, true); const body = at + 8;
    if (tag(at) === 'fmt ') sampleRate = dv.getUint32(body + 4, true);
    if (tag(at) === 'data') { dataAt = body; dataBytes = size; }
    at = body + size + (size & 1);
  }
  if (!sampleRate || dataAt < 0) throw new Error('invalid drum sample WAV');
  const data = new Float32Array(dataBytes / 2);
  for (let i = 0; i < data.length; i++) data[i] = dv.getInt16(dataAt + i * 2, true) / 32768;
  return { sampleRate, data };
}

export async function loadDrumOneShots(): Promise<DrumOneShot[]> {
  return Promise.all(RAW.map(async (s) => ({ name: s.name, ...decodeWavPcm16(await (await fetch(s.url)).arrayBuffer()) })));
}
