// DO NOT EDIT — generated by scripts/build-drum-samples.mjs
#pragma once

#include <cstdint>
#include <vector>

namespace fable {
struct DrumOneShot { const char* name; int sampleRate; const int16_t* data; int length; };
const std::vector<DrumOneShot>& drumOneShots();
} // namespace fable
