// DO NOT EDIT — generated by scripts/build-drum-tables.mjs
//
// Declaration for the sample-derived DR-1 drum tables. Definition (the frame
// data) lives in SampledTables.gen.cpp. Mirrors DrumTables.h.
#pragma once

#include "../../dsp/Wavetables.h"

#include <vector>

namespace fable {

// Exactly 808SD, 808CP, 808CH, 808OH, 808CY in that order.
std::vector<GeneratedTable> generateSampledDrumTables();

} // namespace fable
