// Generated by scripts/generate-clip-library.mjs from shared/seq-clips.json.
// Do not edit by hand.

import type { ClipLibraryEntry } from './clipLibrary';

export const FACTORY_CLIP_LIBRARY = [
    {
      "id": "dr1-neon-drive",
      "name": "NEON DRIVE",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "techno",
      "role": "four-on-floor",
      "energy": 4,
      "tags": [
        "driving",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-house-pocket",
      "name": "HOUSE POCKET",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "four-on-floor",
      "energy": 3,
      "tags": [
        "groovy",
        "straight"
      ],
      "transpose": false
    },
    {
      "id": "dr1-lofi-break",
      "name": "LO-FI BREAK",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAABAAABAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "lo-fi",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "warm",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-cinema-half",
      "name": "CINEMA HALF",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "cinematic",
      "role": "half-time",
      "energy": 2,
      "tags": [
        "dark",
        "sparse"
      ],
      "transpose": false
    },
    {
      "id": "dr1-electro-grid",
      "name": "ELECTRO GRID",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAQAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "electro",
      "role": "electro",
      "energy": 4,
      "tags": [
        "cold",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-perc-orbit",
      "name": "PERC ORBIT",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAQAAAAEAAAIAAAABAAAAAQAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "experimental",
      "role": "percussion",
      "energy": 3,
      "tags": [
        "hypnotic",
        "atonal"
      ],
      "transpose": false
    },
    {
      "id": "dr1-hat-rise",
      "name": "HAT RISE",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQACAQIBAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "build-up",
      "energy": 4,
      "tags": [
        "build-up",
        "dense"
      ],
      "transpose": false
    },
    {
      "id": "dr1-tom-fall",
      "name": "TOM FALL",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAAEAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "cinematic",
      "role": "fill",
      "energy": 5,
      "tags": [
        "dark",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "bl1-acid-crawl",
      "name": "ACID CRAWL",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAAABAAABBQABAAABAAABAQMBAAABAQABAAABAAABBQoAAAABAAABAQUBAAAB",
      "family": "acid",
      "role": "acid",
      "energy": 4,
      "tags": [
        "hypnotic",
        "driving"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-sub-anchor",
      "name": "SUB ANCHOR",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAAABAAABAAABAAABAAABAAABAAABAQoAAAABAAABAAABAAABAAABAAABAAAB",
      "family": "ambient",
      "role": "sub",
      "energy": 1,
      "tags": [
        "dark",
        "sparse"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-neon-arp",
      "name": "NEON ARP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAABAQMBAAABAQcBAAABAQoBAAABAwACAAABAQoBAAABAQcBAAABAQMBAAAB",
      "family": "techno",
      "role": "arpeggio",
      "energy": 4,
      "tags": [
        "bright",
        "dense"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-house-loop",
      "name": "HOUSE LOOP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAABAAABAQABAAABAAABAQMBAAABAQACAAABAAABAQUBAAABAAABAQMBAAAB",
      "family": "house",
      "role": "ostinato",
      "energy": 3,
      "tags": [
        "groovy",
        "hypnotic"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-lofi-skip",
      "name": "LO-FI SKIP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AAABAQABAAABAAABAQoAAAABAAABAQMBAAABAAABAQABAAABAAABAQUBAAABAAAB",
      "family": "lo-fi",
      "role": "syncopated",
      "energy": 3,
      "tags": [
        "warm",
        "syncopated"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-cinema-hold",
      "name": "CINEMA HOLD",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAABQAABQAABQAABQAABQAABQAABQAAAQMABQMABQMABQMABQMABQMABQMABQMA",
      "family": "cinematic",
      "role": "sustained",
      "energy": 2,
      "tags": [
        "dark",
        "breakdown"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-slide-wire",
      "name": "SLIDE WIRE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAAABBQACAAABAQMBBQUBAAABAAABAwoAAAABAQABBQcBAAABAAABAQMBAAAB",
      "family": "acid",
      "role": "sliding",
      "energy": 5,
      "tags": [
        "peak-time",
        "driving"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-minimal-pulse",
      "name": "MINIMAL PULSE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAABAAABAAABAAABAAABAAABAQABAAABAAABAAABAAABAQMBAAABAAABAAAB",
      "family": "experimental",
      "role": "minimal",
      "energy": 2,
      "tags": [
        "cold",
        "sparse"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-glass-hook",
      "name": "GLASS HOOK",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AwACAAABAAABAQoBAAABAAABAQcBAAABAQMCAAABBQoBAAABAAABAAABAQUBAAAB",
      "family": "techno",
      "role": "hook",
      "energy": 4,
      "tags": [
        "bright",
        "melodic"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-air-chord",
      "name": "AIR CHORD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABBQABBQABBQABBQABBQABBQABBQABAQoABQoABQoABQoABQoABQoABQoABQoA",
      "family": "ambient",
      "role": "chord",
      "energy": 1,
      "tags": [
        "warm",
        "breakdown"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-pad-pulse",
      "name": "PAD PULSE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAABAAABAQABAAABAAABAAABAQMBAAABAAABAAABAQoAAAABAAABAAABAQUBAAAB",
      "family": "house",
      "role": "pad-pulse",
      "energy": 3,
      "tags": [
        "warm",
        "groovy"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-lumen-arp",
      "name": "LUMEN ARP",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAABAQMBAAABAQcBAAABAQoBAAABAQACAAABAQMCAAABAQcCAAABAQoCAAAB",
      "family": "techno",
      "role": "arpeggio",
      "energy": 4,
      "tags": [
        "bright",
        "dense"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-fog-lead",
      "name": "FOG LEAD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAABAAABAAABAQoBAAABAAABAQcBAAABAAABAQMBAAABAAABAQUBAAABAAAB",
      "family": "lo-fi",
      "role": "lead",
      "energy": 3,
      "tags": [
        "warm",
        "melodic"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-counter-light",
      "name": "COUNTER LIGHT",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAABAAABAQcBAAABAAABAQoBAAABAAABAAABAQMCAAABAAABAQACAAABAAABAQoB",
      "family": "house",
      "role": "countermelody",
      "energy": 3,
      "tags": [
        "melodic",
        "syncopated"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-cinema-texture",
      "name": "CINEMA TEXTURE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAABAAABBQAAAAABAAABAAABAQUBAAABAAABBQUBAAABAAABAAABAQMBAAAB",
      "family": "cinematic",
      "role": "texture",
      "energy": 2,
      "tags": [
        "dark",
        "atonal"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-signal-rise",
      "name": "SIGNAL RISE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAABAQIBAAABAQMBAAABAQUBAAABAQcBAAABAQgBAAABAQoBAAABAwsCAAAB",
      "family": "cinematic",
      "role": "riser",
      "energy": 5,
      "tags": [
        "build-up",
        "peak-time"
      ],
      "root": 0,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "dr1-dusty-amen",
      "name": "DUSTY AMEN",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAEAAAEAAAABAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAQAAAQABAAEAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "breaks",
      "role": "breakbeat",
      "energy": 4,
      "tags": [
        "warm",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-ghost-shuffle",
      "name": "GHOST SHUFFLE",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "breaks",
      "role": "sparse",
      "energy": 2,
      "tags": [
        "sparse",
        "triplet-feel"
      ],
      "transpose": false
    },
    {
      "id": "dr1-iron-quarters",
      "name": "IRON QUARTERS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAIAAAACAAAAAgAAAAAAAQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "techno",
      "role": "four-on-floor",
      "energy": 5,
      "tags": [
        "driving",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-dub-chambers",
      "name": "DUB CHAMBERS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAABAAEAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "techno",
      "role": "half-time",
      "energy": 3,
      "tags": [
        "dark",
        "hypnotic"
      ],
      "transpose": false
    },
    {
      "id": "dr1-velvet-jack",
      "name": "VELVET JACK",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAACAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "four-on-floor",
      "energy": 3,
      "tags": [
        "warm",
        "groovy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-sunrise-hats",
      "name": "SUNRISE HATS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAEAAQABAAEAAQABAAEAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "hats",
      "energy": 2,
      "tags": [
        "bright",
        "straight"
      ],
      "transpose": false
    },
    {
      "id": "dr1-chrome-sync",
      "name": "CHROME SYNC",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAQAAAAACAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQEAAAEAAQABAQAAAAEAAAABAAEAAQAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "electro",
      "role": "electro",
      "energy": 5,
      "tags": [
        "cold",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-machine-funk",
      "name": "MACHINE FUNK",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAQACAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEBAAABAAEAAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQAAAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "electro",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "groovy",
        "glitchy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-squelch-frame",
      "name": "SQUELCH FRAME",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAIAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "acid",
      "role": "four-on-floor",
      "energy": 4,
      "tags": [
        "driving",
        "hypnotic"
      ],
      "transpose": false
    },
    {
      "id": "dr1-distant-ticks",
      "name": "DISTANT TICKS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "ambient",
      "role": "sparse",
      "energy": 1,
      "tags": [
        "cold",
        "sparse"
      ],
      "transpose": false
    },
    {
      "id": "dr1-tape-swing",
      "name": "TAPE SWING",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAEAAgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAABAAABAAABAAABAAEAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "lo-fi",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "warm",
        "triplet-feel"
      ],
      "transpose": false
    },
    {
      "id": "dr1-titan-march",
      "name": "TITAN MARCH",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAACAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAQACAAAAAAABAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "cinematic",
      "role": "half-time",
      "energy": 5,
      "tags": [
        "dark",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-broken-clock",
      "name": "BROKEN CLOCK",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAABAAABAAABAAAAAQABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAABAAAAAA==",
      "family": "experimental",
      "role": "experimental",
      "energy": 3,
      "tags": [
        "atonal",
        "glitchy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-jungle-sparks",
      "name": "JUNGLE SPARKS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAQAAAQACAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAABAAAAAAIAAQAAAAAAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAAAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "breaks",
      "role": "breakbeat",
      "energy": 5,
      "tags": [
        "dense",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-garage-skip",
      "name": "GARAGE SKIP",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAQACAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "groovy",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-warehouse-fill",
      "name": "WAREHOUSE FILL",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAIAAAACAAAAAgACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEBAQEBAQAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "techno",
      "role": "fill",
      "energy": 5,
      "tags": [
        "build-up",
        "dense"
      ],
      "transpose": false
    },
    {
      "id": "dr1-pulse-dust",
      "name": "PULSE DUST",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "ambient",
      "role": "percussion",
      "energy": 1,
      "tags": [
        "sparse",
        "hypnotic"
      ],
      "transpose": false
    },
    {
      "id": "dr1-ritual-toms",
      "name": "RITUAL TOMS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAQAAAQACAAABAAABAAAAAQAAAAAAAQAAAAEAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "cinematic",
      "role": "percussion",
      "energy": 3,
      "tags": [
        "dark",
        "triplet-feel"
      ],
      "transpose": false
    },
    {
      "id": "dr1-binary-rain",
      "name": "BINARY RAIN",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEBAAEAAAABAQABAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAAEBAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAQAAAAEAAQ==",
      "family": "experimental",
      "role": "experimental",
      "energy": 4,
      "tags": [
        "cold",
        "glitchy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-bedroom-knock",
      "name": "BEDROOM KNOCK",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "lo-fi",
      "role": "half-time",
      "energy": 2,
      "tags": [
        "warm",
        "sparse"
      ],
      "transpose": false
    },
    {
      "id": "dr1-corrosive-build",
      "name": "CORROSIVE BUILD",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAIAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAEAAQABAQEBAAAAAAAAAAAAAQABAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "acid",
      "role": "build-up",
      "energy": 5,
      "tags": [
        "build-up",
        "driving"
      ],
      "transpose": false
    },
    {
      "id": "dr1-robot-fill",
      "name": "ROBOT FILL",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAQACAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAABAAEAAQABAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAQ==",
      "family": "electro",
      "role": "fill",
      "energy": 4,
      "tags": [
        "glitchy",
        "build-up"
      ],
      "transpose": false
    },
    {
      "id": "dr1-halftime-crush",
      "name": "HALFTIME CRUSH",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAAAAAACAAABAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "breaks",
      "role": "half-time",
      "energy": 4,
      "tags": [
        "dark",
        "driving"
      ],
      "transpose": false
    },
    {
      "id": "dr1-disco-lift",
      "name": "DISCO LIFT",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAIAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEBAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "build-up",
      "energy": 5,
      "tags": [
        "bright",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "bl1-redline-acid",
      "name": "REDLINE ACID",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAQABAAAABQMBAQABAAAAAwcBAQoAAwABAAAABQMBAQEBAwoAAAAAAQcBBQMB",
      "family": "acid",
      "role": "acid",
      "energy": 5,
      "tags": [
        "driving",
        "peak-time"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-rubber-dub",
      "name": "RUBBER DUB",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAAAABQABAAAAAAAAAQcAAQABAAAAAAAAAAAABQoAAAAAAAAAAAAA",
      "family": "acid",
      "role": "minimal",
      "energy": 2,
      "tags": [
        "dark",
        "sparse"
      ],
      "root": 2,
      "scale": "dorian",
      "transpose": true
    },
    {
      "id": "bl1-basement-sequence",
      "name": "BASEMENT SEQUENCE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAQABAQEBAQABAAAAAQMBAAAAAQABAAAAAQcAAQEBAQABAAAAAQoAAAAA",
      "family": "techno",
      "role": "ostinato",
      "energy": 4,
      "tags": [
        "cold",
        "hypnotic"
      ],
      "root": 5,
      "scale": "phrygian",
      "transpose": true
    },
    {
      "id": "bl1-deep-root",
      "name": "DEEP ROOT",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAAAAAAAAAQAAAQMAAAAAAAAAAQAAAQAAAAAAAAAAAQUAAQcAAAAAAAAAAQMA",
      "family": "house",
      "role": "sub",
      "energy": 2,
      "tags": [
        "warm",
        "groovy"
      ],
      "root": 7,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-voltage-hop",
      "name": "VOLTAGE HOP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAQcAAAAAAAAAAQMBAwoAAAAAAQABAAAAAAAAAQEBAAAABQcAAAAAAQoA",
      "family": "electro",
      "role": "syncopated",
      "energy": 4,
      "tags": [
        "syncopated",
        "glitchy"
      ],
      "root": 9,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-rewind-bass",
      "name": "REWIND BASS",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAQMBAQABAAAAAAAAAQoAAQABAAAAAQcAAAAAAQMBAAAAAAAABQAB",
      "family": "breaks",
      "role": "syncopated",
      "energy": 4,
      "tags": [
        "warm",
        "driving"
      ],
      "root": 0,
      "scale": "pentatonic-minor",
      "transpose": true
    },
    {
      "id": "bl1-tide-drone",
      "name": "TIDE DRONE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABBAABBAABBAABAQcABAcABAcABAcAAQUABAUABAUABAUAAQABBAABBAABBAAB",
      "family": "ambient",
      "role": "sustained",
      "energy": 1,
      "tags": [
        "warm",
        "breakdown"
      ],
      "root": 4,
      "scale": "major",
      "transpose": true
    },
    {
      "id": "bl1-cassette-sub",
      "name": "CASSETTE SUB",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAAAAAAAAAQAAAAAAAAAAAQMAAAAAAQAAAAAAAAAAAQoAAAAAAAAAAQcAAAAA",
      "family": "lo-fi",
      "role": "sub",
      "energy": 2,
      "tags": [
        "warm",
        "triplet-feel"
      ],
      "root": 10,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-dread-pedal",
      "name": "DREAD PEDAL",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAABAAABAAABAAABQEAAAAAAAAAAAAAAQAABAAABAAABAAABQcAAAAAAAAAAAAA",
      "family": "cinematic",
      "role": "sustained",
      "energy": 3,
      "tags": [
        "dark",
        "hypnotic"
      ],
      "root": 1,
      "scale": "phrygian",
      "transpose": true
    },
    {
      "id": "bl1-wrong-turn",
      "name": "WRONG TURN",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAAAABQsAAAAAAAAAAwICAAAAAQgABQEBAAAAAwkAAAAAAAAAAQQBAAAABQYA",
      "family": "experimental",
      "role": "sliding",
      "energy": 3,
      "tags": [
        "atonal",
        "glitchy"
      ],
      "root": 6,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "bl1-acid-ascent",
      "name": "ACID ASCENT",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAQAAAQMAAQMAAQUAAQUAAQcAAQcAAwgAAQgAAwoAAQoAAwABAQMBAwcBBQoB",
      "family": "acid",
      "role": "transition",
      "energy": 5,
      "tags": [
        "build-up",
        "dense"
      ],
      "root": 3,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-turnaround-fill",
      "name": "TURNAROUND FILL",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAQMBAQUBAQcBAwoBAQcBAwUBBQMB",
      "family": "house",
      "role": "fill",
      "energy": 4,
      "tags": [
        "groovy",
        "build-up"
      ],
      "root": 5,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-prism-lead",
      "name": "PRISM LEAD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAAAAQMBAQcBAQoBAAAAAQcBAAAAAQACAAAAAQoBAQcBAQMBAAAAAQEBAQAB",
      "family": "techno",
      "role": "lead",
      "energy": 5,
      "tags": [
        "bright",
        "peak-time"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-sodium-chords",
      "name": "SODIUM CHORDS",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABBAABAAAAAQMBAQcBBAcBAAAAAQoBAQACBAACAAAAAQoBAQcBBAcBAAAAAQMB",
      "family": "house",
      "role": "chord",
      "energy": 3,
      "tags": [
        "warm",
        "groovy"
      ],
      "root": 5,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-arcade-hero",
      "name": "ARCADE HERO",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAQMBAAAAAQcBAQACAAAAAQoBAQcBAQMBAAAAAQABAAAAAQcBAQoBAAAAAQAC",
      "family": "electro",
      "role": "hook",
      "energy": 4,
      "tags": [
        "bright",
        "melodic"
      ],
      "root": 9,
      "scale": "pentatonic-minor",
      "transpose": true
    },
    {
      "id": "wt1-rain-counter",
      "name": "RAIN COUNTER",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAAAAQcBAAAAAQoBAAAAAAAAAQMCAQACAAAAAQoBAAAAAQcBAAAAAAAAAQUBAQMB",
      "family": "breaks",
      "role": "countermelody",
      "energy": 3,
      "tags": [
        "syncopated",
        "melodic"
      ],
      "root": 2,
      "scale": "dorian",
      "transpose": true
    },
    {
      "id": "wt1-horizon-pad",
      "name": "HORIZON PAD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAAAAAQcBAAAAAAAAAAAAAQUBAAAAAAAAAAAAAQACAAAAAAAAAAAA",
      "family": "ambient",
      "role": "pad-pulse",
      "energy": 1,
      "tags": [
        "warm",
        "sparse"
      ],
      "root": 4,
      "scale": "major",
      "transpose": true
    },
    {
      "id": "wt1-tape-memory",
      "name": "TAPE MEMORY",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAQMBAAAAAAAAAQcBAAAAAQoBAAAAAAAAAQcBAAAAAAAAAQMBAAAA",
      "family": "lo-fi",
      "role": "lead",
      "energy": 2,
      "tags": [
        "warm",
        "triplet-feel"
      ],
      "root": 10,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-black-signal",
      "name": "BLACK SIGNAL",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAAABQYBAAAAAAAAAQECAAAAAwsAAQABAAAABQgBAAAAAAAAAQICAAAAAwEB",
      "family": "cinematic",
      "role": "texture",
      "energy": 3,
      "tags": [
        "dark",
        "atonal"
      ],
      "root": 1,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "wt1-shard-cloud",
      "name": "SHARD CLOUD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQACAQsAAAAABQUBAQICAAAAAwkAAAAAAAAAAQMCAAAABQgAAQEBAAAAAwcCAAAA",
      "family": "experimental",
      "role": "texture",
      "energy": 4,
      "tags": [
        "cold",
        "glitchy"
      ],
      "root": 6,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "wt1-acid-answer",
      "name": "ACID ANSWER",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAAAAQcBAAAAAwoBAAAAAQMCAAAABQECAAAAAQoBAAAAAwcBAAAAAQUBAAAABQMB",
      "family": "acid",
      "role": "countermelody",
      "energy": 4,
      "tags": [
        "hypnotic",
        "melodic"
      ],
      "root": 3,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-aurora-rise",
      "name": "AURORA RISE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAQEAAQIAAQMAAQQAAQUAAQYAAQcAAQgBAQkBAQoBAQsBAQACAQMCAQcCBQoC",
      "family": "cinematic",
      "role": "riser",
      "energy": 5,
      "tags": [
        "build-up",
        "bright"
      ],
      "root": 0,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "wt1-subway-bass",
      "name": "SUBWAY BASS",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAAAAQAAAAAAAQEAAAAAAQMAAAAAAQAAAAAAAQcAAAAAAQEAAAAAAQoAAAAA",
      "family": "techno",
      "role": "bass",
      "energy": 3,
      "tags": [
        "dark",
        "driving"
      ],
      "root": 7,
      "scale": "phrygian",
      "transpose": true
    },
    {
      "id": "wt1-doorway-transition",
      "name": "DOORWAY TRANSITION",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAAAAQIAAAAAAQUAAAAAAQkAAAAAAwEBAAAAAwYBAAAABQsBAwQCBQgCAQAC",
      "family": "experimental",
      "role": "transition",
      "energy": 4,
      "tags": [
        "build-up",
        "atonal"
      ],
      "root": 8,
      "scale": "chromatic",
      "transpose": true
    }
  ] satisfies readonly ClipLibraryEntry[];

export const FACTORY_CLIP_BYTE_FINGERPRINTS = {
  "dr1-neon-drive": "50f62ffc779a98c4199c99a20ce99b5b7f2d4ddf07581b024f1f97db1b227bde",
  "dr1-house-pocket": "a0360813b83e5394f3ec9019608a813f2f9ca2806d26388f36936e1dd10ac3b8",
  "dr1-lofi-break": "58edebc24fef06c7085bcd70909826eed569f0c67b9229e3ef71ae031f05f1b0",
  "dr1-cinema-half": "79266c32ea0136bb281a1aafa89dbb4422f697afab296e7c603d09c0916bf87c",
  "dr1-electro-grid": "ca1c9d778ef9ca7fc2c9e43fede524760a21206cc1b5aaf24c747b4f1147e926",
  "dr1-perc-orbit": "49f6ddf8a476d779ff0f2f89d5dd7030cca7a4af3e5ae86fdd5668c4e743fd64",
  "dr1-hat-rise": "826043ba93dbb1392eb8789a179b4ae5dbbb7ed878da4ef4003c9a612c5246cb",
  "dr1-tom-fall": "a9d30c8748d2d0b115f8e9ad504dcba6ffc4a05234e4115796f4c3f82502cf36",
  "bl1-acid-crawl": "233da650c0933bbeecbe02fcb261952df7c5b0eacec7dce3734fd2dabdd65903",
  "bl1-sub-anchor": "20e60f8f4709591f6f737d83f2fc669681e1c2d2d9ae53716c017ec7c5ae9b5f",
  "bl1-neon-arp": "8006b43373292f126437ce18bd53a6840718b97217ea8f489532f425f763e295",
  "bl1-house-loop": "2e0d077768faed33fc5920b9a63c1afec4bce7fb19174ecfb36590969b54b922",
  "bl1-lofi-skip": "8bf0f3c311979d6cb6be39258144c25e54afd155ea6dae2297ec9d0e0a691590",
  "bl1-cinema-hold": "1867400fa3b9928c16401a76a7e9394baeeeee4ed64adbe899ed11d97a79b29f",
  "bl1-slide-wire": "6ed2392210397ec49fbf6669cbfce9616a593e88e98f803f973cdccfb27e4509",
  "bl1-minimal-pulse": "7a321ea5d7720fcaf65e2070bc7af8994abada4373b44bf4695f8309570e24b9",
  "wt1-glass-hook": "3839c691673a6e43a59a304d42557e7250755ce2b0a55c46d2e1da3adb93ee90",
  "wt1-air-chord": "57719d1e16a7dea66b7dfeb1ab31a617e27cd42f5ce81be7053a7c3a8ae078bd",
  "wt1-pad-pulse": "c859fd663d9a81a6883c4a90a905724aed83443d11afd95c68c47432c6830d39",
  "wt1-lumen-arp": "a5f43de94b0e2d4f38cc55be5d2b6b917d3b38d0373d7376c6c695f61c130dce",
  "wt1-fog-lead": "c1ae65b57bb8caac6a5b64805dec6c5cb8e400b0c6b35969e0db850044395fa9",
  "wt1-counter-light": "b89a3f0aacfded571b151abcccbc980d21099717ab4f663f20217d6978d8a098",
  "wt1-cinema-texture": "d783beaaf9b246ab7f7d1c234a2e83a61c9ccaf3cabc68454874d9a1d65065e9",
  "wt1-signal-rise": "74247214e7b70401928ba5252c4e4553983e78a38d4332dd7c88815b39872fae",
  "dr1-dusty-amen": "d1816a69526dccf1b684576acee3949d90cd31642f6b6f48f21b41af8989e0e5",
  "dr1-ghost-shuffle": "5ef1aadcb2da48a95a19cdda33800103c067506e6dcc76e44b60e57da2d8c59b",
  "dr1-iron-quarters": "2a32996911c0b34b5b8b35dfc6798da911a2b97bc28a99f2335994b68f1f4f60",
  "dr1-dub-chambers": "99a4040531a65030672d8e28760807adaa0a9ae86dae9d06e598660d70eedecf",
  "dr1-velvet-jack": "2d5f9220c4d875752215718aa8a73b43bb8a46956ad7d687ecc2a68498c17cc9",
  "dr1-sunrise-hats": "4ca7ef8742b16b1f0269cca15945cddc493797ce092db24c7afc9894b0609ef2",
  "dr1-chrome-sync": "bf13121afc6259c8c1a8b4cec2dbc27e70ed27649a8b1ff45bcadfbaf0b2a34c",
  "dr1-machine-funk": "ea0033077df88efdbc755ff8c463942b1090f1964be6af9836841be9b864f73d",
  "dr1-squelch-frame": "9053df60db94f265705fd867be6d603c0eedb48ed7e668c7ee1a331640e9ad4a",
  "dr1-distant-ticks": "36e42c753fb4c24670634f59747cb4f66469397cea257985ad7f82838a7f4afb",
  "dr1-tape-swing": "4c7791436222c8181e0dc98c97bf84f11a7e228f4cf21f6f36c8c625b2d69f2a",
  "dr1-titan-march": "0e848657188a365cf8013a2e7f29d8414b7bf54e985cb80eb60230c92b05cce4",
  "dr1-broken-clock": "4a6d41927a07a1b1f64b1a5b619967c16f76b72dd459b9a71f83e84e107b098a",
  "dr1-jungle-sparks": "2b5cf27bf9416fdf41d076e032159cb502320988ed8143833d5242b0c6d32442",
  "dr1-garage-skip": "174931d4ef087c5c7d54148994ed87621f6ecf27df90a6de45f5c775859cd2cd",
  "dr1-warehouse-fill": "2fab3e9c7fce65d5b181d6b9871cffbbd1038d60280bfcd8b72a9a83fa696bca",
  "dr1-pulse-dust": "6278a4ced2ff919e80c7c45561b135fc48465477688b5835dc8bc2b76893116f",
  "dr1-ritual-toms": "1ff09ba7878285f76bc56b59d4f5c3d4a1dd026a891d054ebc788cc4e8614f45",
  "dr1-binary-rain": "032cd14729b8033b2479d179279e9ff607c7228c963aba8717d0b469429cb6f4",
  "dr1-bedroom-knock": "c4ee1a42b8d2e82d1f802b8f6dd2946607d415b3174287d54705155477146a79",
  "dr1-corrosive-build": "80774d09ac5704bfab507a723fafd28a5a1f5e1aec621b3995c4c823ebe4e592",
  "dr1-robot-fill": "7610b1fcf65448d5a98ff39e0e7bb110aaa4dc48fad730a48f62b1f1e2f37e51",
  "dr1-halftime-crush": "5e64254f3c851585f4baaa8759426c6065180ded63b4f7f8775760046f396187",
  "dr1-disco-lift": "1d1ab1caa38390dca188a50beea50244741decc23fe759defcac2f8560670a1c",
  "bl1-redline-acid": "d830389a5ae528bbcb9232b3aef327d4b16f4b80a20975ee6bd95a509f9ddc4c",
  "bl1-rubber-dub": "63a92e42ddbc9fe4be62e1fff154c58a561530bdb7c0f9a7ab1697a68349723e",
  "bl1-basement-sequence": "d34f8d389036c60018c54e79cafd185cbc2e011c6f36cd5436f761e33697299c",
  "bl1-deep-root": "ee03f12c80216a04238df3e0e048a6341a4e3fb0d6121369789434d3b8af2e10",
  "bl1-voltage-hop": "2e597c888c4cbeee0a8a5cfb0b16b2494ebdd12a468a506646f508bdb6efeb94",
  "bl1-rewind-bass": "028a212af63530a1a360679b5d5ee5e2947f50317ee374200038db03acd337ba",
  "bl1-tide-drone": "7c9d7846eeca4dc4315785b5f04f6098127bc509065a7d1d4c26461669545c61",
  "bl1-cassette-sub": "b0b1fd58054938f91faf2f1fe4887f07043ad9b886af5238a9dde3fd6a2ed661",
  "bl1-dread-pedal": "f2d27cf3e66ac2f9b271874afe964909b1c306fa90c663ff88738afd9076f24c",
  "bl1-wrong-turn": "6c9684bc4094d2d756900627752a3704878476d1f5a61fb847c8f92eb3c57fc6",
  "bl1-acid-ascent": "a8ab3efb01f75822c6030850446b87be0107c3b0b643c6c9e6248fb8c2c9227c",
  "bl1-turnaround-fill": "fe78e42116bdde5b4ee8f94de2ff6bc1c9c2b03da8a754e5349561805c06bc01",
  "wt1-prism-lead": "9376cf88db448a5af061afc8712e7f20b8459811deedb2c3ed6808b32bcb741e",
  "wt1-sodium-chords": "14af4a744a8e1ee12252f95cfb32714a1e8c0ea12de1d58fcf5454dcd4fb7982",
  "wt1-arcade-hero": "d734d2cb54dbe4a05c689ed6e99fe05d4fbd31992c38116c99c22dc9a664cb1c",
  "wt1-rain-counter": "f07a952181b568ea361fae02f0189eb47f5ed1e0eddee2201c0ebc9e6297c16c",
  "wt1-horizon-pad": "fae0c363cfcc878f6ce372f76409bd1fc48c4d13e71fa7196b9145273bb594b6",
  "wt1-tape-memory": "3af5e8f3b2f3c1d3759c54a704a7837634a5beb35375466d4b9b4c87eb4a8b97",
  "wt1-black-signal": "13825fd1e5bbf671c30f5527629194b8e35e3f9320ae3796d24f73ec1199ae36",
  "wt1-shard-cloud": "bde4361007d065f54d63eac9c665d310527a7debe5d305415830daaae873155e",
  "wt1-acid-answer": "69e4e2e17232310373042664fb640a25ca4703ec08a7971cda8d6660d1396ada",
  "wt1-aurora-rise": "ae1c9091e000ae7e74391f896c971bcc1925792c8bf26590a6f376367052696c",
  "wt1-subway-bass": "9ac684f91eb2f6b06755ed383049ca00d88b8411d4303cfe15f782a4a03d9767",
  "wt1-doorway-transition": "ccae1ebb163ce6fd3fef30a3e2be92285b67ac8b2a2c5f6ccbf7cdd87a856ada"
} as const;
