// Generated by scripts/generate-clip-library.mjs from shared/seq-clips.json.
// Do not edit by hand.

import type { ClipLibraryEntry } from './clipLibrary';

export const FACTORY_CLIP_LIBRARY = [
    {
      "id": "dr1-neon-drive",
      "name": "HYBRID DRIVE",
      "machine": "DR1",
      "bars": 2,
      "pattern": "AgAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAABAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
      "family": "techno",
      "role": "four-on-floor",
      "energy": 4,
      "tags": [
        "driving",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-house-pocket",
      "name": "808 FLOOR",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "four-on-floor",
      "energy": 3,
      "tags": [
        "groovy",
        "straight"
      ],
      "transpose": false
    },
    {
      "id": "dr1-lofi-break",
      "name": "UZU BREAK",
      "machine": "DR1",
      "bars": 2,
      "pattern": "AQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE=",
      "family": "lo-fi",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "warm",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-cinema-half",
      "name": "HALF LAYERS",
      "machine": "DR1",
      "bars": 2,
      "pattern": "AgAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA=",
      "family": "cinematic",
      "role": "half-time",
      "energy": 2,
      "tags": [
        "dark",
        "sparse"
      ],
      "transpose": false
    },
    {
      "id": "dr1-electro-grid",
      "name": "CROSSWIRE GRID",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAQAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQ==",
      "family": "electro",
      "role": "electro",
      "energy": 4,
      "tags": [
        "cold",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-perc-orbit",
      "name": "MODULAR ORBIT",
      "machine": "DR1",
      "bars": 2,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAABAAAAAAABAAAAAAAAAAEAAAAAAQAAAAAAAQAAAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAQA=",
      "family": "experimental",
      "role": "percussion",
      "energy": 3,
      "tags": [
        "hypnotic",
        "atonal"
      ],
      "transpose": false
    },
    {
      "id": "dr1-hat-rise",
      "name": "DUAL HAT RISE",
      "machine": "DR1",
      "bars": 3,
      "pattern": "AQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAIAAQABAAEAAgABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQECAQEBAQEBAQIBAQEAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "family": "house",
      "role": "build-up",
      "energy": 4,
      "tags": [
        "build-up",
        "dense"
      ],
      "transpose": false
    },
    {
      "id": "dr1-tom-fall",
      "name": "TOM CASCADE",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "cinematic",
      "role": "fill",
      "energy": 5,
      "tags": [
        "dark",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "bl1-acid-crawl",
      "name": "ACID CRAWL",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAAABAAABBQABAAABAAABAQMBAAABAQABAAABAAABBQoAAAABAAABAQUBAAAB",
      "family": "acid",
      "role": "acid",
      "energy": 4,
      "tags": [
        "hypnotic",
        "driving"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-sub-anchor",
      "name": "SUB ANCHOR",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAAABAAABAAABAAABAAABAAABAAABAQoAAAABAAABAAABAAABAAABAAABAAAB",
      "family": "ambient",
      "role": "sub",
      "energy": 1,
      "tags": [
        "dark",
        "sparse"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-neon-arp",
      "name": "NEON ARP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAABAQMBAAABAQcBAAABAQoBAAABAwACAAABAQoBAAABAQcBAAABAQMBAAAB",
      "family": "techno",
      "role": "arpeggio",
      "energy": 4,
      "tags": [
        "bright",
        "dense"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-house-loop",
      "name": "HOUSE LOOP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAABAAABAQABAAABAAABAQMBAAABAQACAAABAAABAQUBAAABAAABAQMBAAAB",
      "family": "house",
      "role": "ostinato",
      "energy": 3,
      "tags": [
        "groovy",
        "hypnotic"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-lofi-skip",
      "name": "LO-FI SKIP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AAABAQABAAABAAABAQoAAAABAAABAQMBAAABAAABAQABAAABAAABAQUBAAABAAAB",
      "family": "lo-fi",
      "role": "syncopated",
      "energy": 3,
      "tags": [
        "warm",
        "syncopated"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-cinema-hold",
      "name": "CINEMA HOLD",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAABQAABQAABQAABQAABQAABQAABQAAAQMABQMABQMABQMABQMABQMABQMABQMA",
      "family": "cinematic",
      "role": "sustained",
      "energy": 2,
      "tags": [
        "dark",
        "breakdown"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-slide-wire",
      "name": "SLIDE WIRE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAAABBQACAAABAQMBBQUBAAABAAABAwoAAAABAQABBQcBAAABAAABAQMBAAAB",
      "family": "acid",
      "role": "sliding",
      "energy": 5,
      "tags": [
        "peak-time",
        "driving"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-minimal-pulse",
      "name": "MINIMAL PULSE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAABAAABAAABAAABAAABAAABAQABAAABAAABAAABAAABAQMBAAABAAABAAAB",
      "family": "experimental",
      "role": "minimal",
      "energy": 2,
      "tags": [
        "cold",
        "sparse"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-glass-hook",
      "name": "GLASS HOOK",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AwACAAABAAABAQoBAAABAAABAQcBAAABAQMCAAABBQoBAAABAAABAAABAQUBAAAB",
      "family": "techno",
      "role": "hook",
      "energy": 4,
      "tags": [
        "bright",
        "melodic"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-air-chord",
      "name": "AIR CHORD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABBQABBQABBQABBQABBQABBQABBQABAQoABQoABQoABQoABQoABQoABQoABQoA",
      "family": "ambient",
      "role": "chord",
      "energy": 1,
      "tags": [
        "warm",
        "breakdown"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-pad-pulse",
      "name": "PAD PULSE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAABAAABAQABAAABAAABAAABAQMBAAABAAABAAABAQoAAAABAAABAAABAQUBAAAB",
      "family": "house",
      "role": "pad-pulse",
      "energy": 3,
      "tags": [
        "warm",
        "groovy"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-lumen-arp",
      "name": "LUMEN ARP",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAABAQMBAAABAQcBAAABAQoBAAABAQACAAABAQMCAAABAQcCAAABAQoCAAAB",
      "family": "techno",
      "role": "arpeggio",
      "energy": 4,
      "tags": [
        "bright",
        "dense"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-fog-lead",
      "name": "FOG LEAD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAABAAABAAABAQoBAAABAAABAQcBAAABAAABAQMBAAABAAABAQUBAAABAAAB",
      "family": "lo-fi",
      "role": "lead",
      "energy": 3,
      "tags": [
        "warm",
        "melodic"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-counter-light",
      "name": "COUNTER LIGHT",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAABAAABAQcBAAABAAABAQoBAAABAAABAAABAQMCAAABAAABAQACAAABAAABAQoB",
      "family": "house",
      "role": "countermelody",
      "energy": 3,
      "tags": [
        "melodic",
        "syncopated"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-cinema-texture",
      "name": "CINEMA TEXTURE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAABAAABBQAAAAABAAABAAABAQUBAAABAAABBQUBAAABAAABAAABAQMBAAAB",
      "family": "cinematic",
      "role": "texture",
      "energy": 2,
      "tags": [
        "dark",
        "atonal"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-signal-rise",
      "name": "SIGNAL RISE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAABAQIBAAABAQMBAAABAQUBAAABAQcBAAABAQgBAAABAQoBAAABAwsCAAAB",
      "family": "cinematic",
      "role": "riser",
      "energy": 5,
      "tags": [
        "build-up",
        "peak-time"
      ],
      "root": 0,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "dr1-dusty-amen",
      "name": "UZU AMEN",
      "machine": "DR1",
      "bars": 2,
      "pattern": "AQAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAABAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAAEAAAAAAAAAAAEAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQE=",
      "family": "breaks",
      "role": "breakbeat",
      "energy": 4,
      "tags": [
        "warm",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-ghost-shuffle",
      "name": "GHOST RIM",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAQAAAQAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "breaks",
      "role": "sparse",
      "energy": 2,
      "tags": [
        "sparse",
        "triplet-feel"
      ],
      "transpose": false
    },
    {
      "id": "dr1-iron-quarters",
      "name": "808 PRESSURE",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAACAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQIBAQECAQEBAgEBAQIBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "techno",
      "role": "four-on-floor",
      "energy": 5,
      "tags": [
        "driving",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-dub-chambers",
      "name": "DUB SPACE",
      "machine": "DR1",
      "bars": 2,
      "pattern": "AQAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA=",
      "family": "techno",
      "role": "half-time",
      "energy": 3,
      "tags": [
        "dark",
        "hypnotic"
      ],
      "transpose": false
    },
    {
      "id": "dr1-velvet-jack",
      "name": "UZU JACK",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "four-on-floor",
      "energy": 3,
      "tags": [
        "warm",
        "groovy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-sunrise-hats",
      "name": "AIR HATS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAgABAAEAAQACAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "hats",
      "energy": 2,
      "tags": [
        "bright",
        "straight"
      ],
      "transpose": false
    },
    {
      "id": "dr1-chrome-sync",
      "name": "ELECTRO METAL",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAQAAAAABAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQ==",
      "family": "electro",
      "role": "electro",
      "energy": 5,
      "tags": [
        "cold",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-machine-funk",
      "name": "MACHINE SHUFFLE",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ==",
      "family": "electro",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "groovy",
        "glitchy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-squelch-frame",
      "name": "ACID HYBRID",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "acid",
      "role": "four-on-floor",
      "energy": 4,
      "tags": [
        "driving",
        "hypnotic"
      ],
      "transpose": false
    },
    {
      "id": "dr1-distant-ticks",
      "name": "SAMPLE TICKS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ==",
      "family": "ambient",
      "role": "sparse",
      "energy": 1,
      "tags": [
        "cold",
        "sparse"
      ],
      "transpose": false
    },
    {
      "id": "dr1-tape-swing",
      "name": "TAPE CROSS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "lo-fi",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "warm",
        "triplet-feel"
      ],
      "transpose": false
    },
    {
      "id": "dr1-titan-march",
      "name": "TITAN HYBRID",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "cinematic",
      "role": "half-time",
      "energy": 5,
      "tags": [
        "dark",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-broken-clock",
      "name": "BROKEN MOD",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAQ==",
      "family": "experimental",
      "role": "experimental",
      "energy": 3,
      "tags": [
        "atonal",
        "glitchy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-jungle-sparks",
      "name": "JUNGLE UZU",
      "machine": "DR1",
      "bars": 2,
      "pattern": "AQAAAQAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAAABAAACAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAABAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAABAAAAAQAAAAAAAAEAAAABAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAgEBAQIBAQECAQEBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE=",
      "family": "breaks",
      "role": "breakbeat",
      "energy": 5,
      "tags": [
        "dense",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "dr1-garage-skip",
      "name": "GARAGE HYBRID",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAABAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "breakbeat",
      "energy": 3,
      "tags": [
        "groovy",
        "syncopated"
      ],
      "transpose": false
    },
    {
      "id": "dr1-warehouse-fill",
      "name": "WAREHOUSE ROLL",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "techno",
      "role": "fill",
      "energy": 5,
      "tags": [
        "build-up",
        "dense"
      ],
      "transpose": false
    },
    {
      "id": "dr1-pulse-dust",
      "name": "COWBELL DUST",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ==",
      "family": "ambient",
      "role": "percussion",
      "energy": 1,
      "tags": [
        "sparse",
        "hypnotic"
      ],
      "transpose": false
    },
    {
      "id": "dr1-ritual-toms",
      "name": "TOM RITUAL",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "cinematic",
      "role": "percussion",
      "energy": 3,
      "tags": [
        "dark",
        "triplet-feel"
      ],
      "transpose": false
    },
    {
      "id": "dr1-binary-rain",
      "name": "BINARY UZU",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAABAQAAAQABAAABAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAQ==",
      "family": "experimental",
      "role": "experimental",
      "energy": 4,
      "tags": [
        "cold",
        "glitchy"
      ],
      "transpose": false
    },
    {
      "id": "dr1-bedroom-knock",
      "name": "BEDROOM 808",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "lo-fi",
      "role": "half-time",
      "energy": 2,
      "tags": [
        "warm",
        "sparse"
      ],
      "transpose": false
    },
    {
      "id": "dr1-corrosive-build",
      "name": "CORROSIVE MIX",
      "machine": "DR1",
      "bars": 3,
      "pattern": "AQAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAEAAQABAAEAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQAAAAIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "family": "acid",
      "role": "build-up",
      "energy": 5,
      "tags": [
        "build-up",
        "driving"
      ],
      "transpose": false
    },
    {
      "id": "dr1-robot-fill",
      "name": "ROBOT CROSS",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAg==",
      "family": "electro",
      "role": "fill",
      "energy": 4,
      "tags": [
        "glitchy",
        "build-up"
      ],
      "transpose": false
    },
    {
      "id": "dr1-halftime-crush",
      "name": "HALFTIME UZU",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AQAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "breaks",
      "role": "half-time",
      "energy": 4,
      "tags": [
        "dark",
        "driving"
      ],
      "transpose": false
    },
    {
      "id": "dr1-disco-lift",
      "name": "DISCO HYBRID",
      "machine": "DR1",
      "bars": 1,
      "pattern": "AgAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAQIBAQECAQEBAgEBAQIBAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
      "family": "house",
      "role": "build-up",
      "energy": 5,
      "tags": [
        "bright",
        "peak-time"
      ],
      "transpose": false
    },
    {
      "id": "bl1-redline-acid",
      "name": "REDLINE ACID",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAQABAAAABQMBAQABAAAAAwcBAQoAAwABAAAABQMBAQEBAwoAAAAAAQcBBQMB",
      "family": "acid",
      "role": "acid",
      "energy": 5,
      "tags": [
        "driving",
        "peak-time"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-rubber-dub",
      "name": "RUBBER DUB",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAAAABQABAAAAAAAAAQcAAQABAAAAAAAAAAAABQoAAAAAAAAAAAAA",
      "family": "acid",
      "role": "minimal",
      "energy": 2,
      "tags": [
        "dark",
        "sparse"
      ],
      "root": 2,
      "scale": "dorian",
      "transpose": true
    },
    {
      "id": "bl1-basement-sequence",
      "name": "BASEMENT SEQUENCE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAQABAQEBAQABAAAAAQMBAAAAAQABAAAAAQcAAQEBAQABAAAAAQoAAAAA",
      "family": "techno",
      "role": "ostinato",
      "energy": 4,
      "tags": [
        "cold",
        "hypnotic"
      ],
      "root": 5,
      "scale": "phrygian",
      "transpose": true
    },
    {
      "id": "bl1-deep-root",
      "name": "DEEP ROOT",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAAAAAAAAAQAAAQMAAAAAAAAAAQAAAQAAAAAAAAAAAQUAAQcAAAAAAAAAAQMA",
      "family": "house",
      "role": "sub",
      "energy": 2,
      "tags": [
        "warm",
        "groovy"
      ],
      "root": 7,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-voltage-hop",
      "name": "VOLTAGE HOP",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAQcAAAAAAAAAAQMBAwoAAAAAAQABAAAAAAAAAQEBAAAABQcAAAAAAQoA",
      "family": "electro",
      "role": "syncopated",
      "energy": 4,
      "tags": [
        "syncopated",
        "glitchy"
      ],
      "root": 9,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-rewind-bass",
      "name": "REWIND BASS",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAQMBAQABAAAAAAAAAQoAAQABAAAAAQcAAAAAAQMBAAAAAAAABQAB",
      "family": "breaks",
      "role": "syncopated",
      "energy": 4,
      "tags": [
        "warm",
        "driving"
      ],
      "root": 0,
      "scale": "pentatonic-minor",
      "transpose": true
    },
    {
      "id": "bl1-tide-drone",
      "name": "TIDE DRONE",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQABBAABBAABBAABAQcABAcABAcABAcAAQUABAUABAUABAUAAQABBAABBAABBAAB",
      "family": "ambient",
      "role": "sustained",
      "energy": 1,
      "tags": [
        "warm",
        "breakdown"
      ],
      "root": 4,
      "scale": "major",
      "transpose": true
    },
    {
      "id": "bl1-cassette-sub",
      "name": "CASSETTE SUB",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAAAAAAAAAQAAAAAAAAAAAQMAAAAAAQAAAAAAAAAAAQoAAAAAAAAAAQcAAAAA",
      "family": "lo-fi",
      "role": "sub",
      "energy": 2,
      "tags": [
        "warm",
        "triplet-feel"
      ],
      "root": 10,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-dread-pedal",
      "name": "DREAD PEDAL",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAABAAABAAABAAABQEAAAAAAAAAAAAAAQAABAAABAAABAAABQcAAAAAAAAAAAAA",
      "family": "cinematic",
      "role": "sustained",
      "energy": 3,
      "tags": [
        "dark",
        "hypnotic"
      ],
      "root": 1,
      "scale": "phrygian",
      "transpose": true
    },
    {
      "id": "bl1-wrong-turn",
      "name": "WRONG TURN",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AwABAAAABQsAAAAAAAAAAwICAAAAAQgABQEBAAAAAwkAAAAAAAAAAQQBAAAABQYA",
      "family": "experimental",
      "role": "sliding",
      "energy": 3,
      "tags": [
        "atonal",
        "glitchy"
      ],
      "root": 6,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "bl1-acid-ascent",
      "name": "ACID ASCENT",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AQAAAQAAAQMAAQMAAQUAAQUAAQcAAQcAAwgAAQgAAwoAAQoAAwABAQMBAwcBBQoB",
      "family": "acid",
      "role": "transition",
      "energy": 5,
      "tags": [
        "build-up",
        "dense"
      ],
      "root": 3,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "bl1-turnaround-fill",
      "name": "TURNAROUND FILL",
      "machine": "BL1",
      "bars": 1,
      "pattern": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAQMBAQUBAQcBAwoBAQcBAwUBBQMB",
      "family": "house",
      "role": "fill",
      "energy": 4,
      "tags": [
        "groovy",
        "build-up"
      ],
      "root": 5,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-prism-lead",
      "name": "PRISM LEAD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAAAAQMBAQcBAQoBAAAAAQcBAAAAAQACAAAAAQoBAQcBAQMBAAAAAQEBAQAB",
      "family": "techno",
      "role": "lead",
      "energy": 5,
      "tags": [
        "bright",
        "peak-time"
      ],
      "root": 0,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-sodium-chords",
      "name": "SODIUM CHORDS",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABBAABAAAAAQMBAQcBBAcBAAAAAQoBAQACBAACAAAAAQoBAQcBBAcBAAAAAQMB",
      "family": "house",
      "role": "chord",
      "energy": 3,
      "tags": [
        "warm",
        "groovy"
      ],
      "root": 5,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-arcade-hero",
      "name": "ARCADE HERO",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAQMBAAAAAQcBAQACAAAAAQoBAQcBAQMBAAAAAQABAAAAAQcBAQoBAAAAAQAC",
      "family": "electro",
      "role": "hook",
      "energy": 4,
      "tags": [
        "bright",
        "melodic"
      ],
      "root": 9,
      "scale": "pentatonic-minor",
      "transpose": true
    },
    {
      "id": "wt1-rain-counter",
      "name": "RAIN COUNTER",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAAAAQcBAAAAAQoBAAAAAAAAAQMCAQACAAAAAQoBAAAAAQcBAAAAAAAAAQUBAQMB",
      "family": "breaks",
      "role": "countermelody",
      "energy": 3,
      "tags": [
        "syncopated",
        "melodic"
      ],
      "root": 2,
      "scale": "dorian",
      "transpose": true
    },
    {
      "id": "wt1-horizon-pad",
      "name": "HORIZON PAD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAAAAAQcBAAAAAAAAAAAAAQUBAAAAAAAAAAAAAQACAAAAAAAAAAAA",
      "family": "ambient",
      "role": "pad-pulse",
      "energy": 1,
      "tags": [
        "warm",
        "sparse"
      ],
      "root": 4,
      "scale": "major",
      "transpose": true
    },
    {
      "id": "wt1-tape-memory",
      "name": "TAPE MEMORY",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQABAAAAAAAAAQMBAAAAAAAAAQcBAAAAAQoBAAAAAAAAAQcBAAAAAAAAAQMBAAAA",
      "family": "lo-fi",
      "role": "lead",
      "energy": 2,
      "tags": [
        "warm",
        "triplet-feel"
      ],
      "root": 10,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-black-signal",
      "name": "BLACK SIGNAL",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAAABQYBAAAAAAAAAQECAAAAAwsAAQABAAAABQgBAAAAAAAAAQICAAAAAwEB",
      "family": "cinematic",
      "role": "texture",
      "energy": 3,
      "tags": [
        "dark",
        "atonal"
      ],
      "root": 1,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "wt1-shard-cloud",
      "name": "SHARD CLOUD",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQACAQsAAAAABQUBAQICAAAAAwkAAAAAAAAAAQMCAAAABQgAAQEBAAAAAwcCAAAA",
      "family": "experimental",
      "role": "texture",
      "energy": 4,
      "tags": [
        "cold",
        "glitchy"
      ],
      "root": 6,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "wt1-acid-answer",
      "name": "ACID ANSWER",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AAAAAQcBAAAAAwoBAAAAAQMCAAAABQECAAAAAQoBAAAAAwcBAAAAAQUBAAAABQMB",
      "family": "acid",
      "role": "countermelody",
      "energy": 4,
      "tags": [
        "hypnotic",
        "melodic"
      ],
      "root": 3,
      "scale": "minor",
      "transpose": true
    },
    {
      "id": "wt1-aurora-rise",
      "name": "AURORA RISE",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAQEAAQIAAQMAAQQAAQUAAQYAAQcAAQgBAQkBAQoBAQsBAQACAQMCAQcCBQoC",
      "family": "cinematic",
      "role": "riser",
      "energy": 5,
      "tags": [
        "build-up",
        "bright"
      ],
      "root": 0,
      "scale": "chromatic",
      "transpose": true
    },
    {
      "id": "wt1-subway-bass",
      "name": "SUBWAY BASS",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAAAAQAAAAAAAQEAAAAAAQMAAAAAAQAAAAAAAQcAAAAAAQEAAAAAAQoAAAAA",
      "family": "techno",
      "role": "bass",
      "energy": 3,
      "tags": [
        "dark",
        "driving"
      ],
      "root": 7,
      "scale": "phrygian",
      "transpose": true
    },
    {
      "id": "wt1-doorway-transition",
      "name": "DOORWAY TRANSITION",
      "machine": "WT1",
      "bars": 1,
      "pattern": "AQAAAAAAAQIAAAAAAQUAAAAAAQkAAAAAAwEBAAAAAwYBAAAABQsBAwQCBQgCAQAC",
      "family": "experimental",
      "role": "transition",
      "energy": 4,
      "tags": [
        "build-up",
        "atonal"
      ],
      "root": 8,
      "scale": "chromatic",
      "transpose": true
    }
  ] satisfies readonly ClipLibraryEntry[];

export const FACTORY_CLIP_BYTE_FINGERPRINTS = {
  "dr1-neon-drive": "3dd89b3548b4eec30a969ff3226f65bfbc2fb7dfb3572fe04ac67c9a04e1862f",
  "dr1-house-pocket": "8837b68fb81d98e75dccd87b88a0ecc970bfc0a58240381d44a189763dc98e22",
  "dr1-lofi-break": "0340769f177c41fca36f8bd0c0474ab944c1344348a3d6dfee8c7f1bf614f096",
  "dr1-cinema-half": "97b138ead434af706345d33c887bbf0a5b142d145dfc21554647d1902e657d4e",
  "dr1-electro-grid": "6ca477c491e11c2688b75843a364ae3a59cec3f9f49ab05c4d1b7cc74d49eb30",
  "dr1-perc-orbit": "0542948b63f8df2629f535e7ae1f5700fb1acd47dfe45caf6717c45db9b0f34e",
  "dr1-hat-rise": "d9fe21dfcc51b32e6680cfa1922a2830abd52a49bb50a569470b37d36622ce8c",
  "dr1-tom-fall": "fa2ec458e9021293feebbbae03f7ba52303c2b598b97b63d61ca4446a08c10dc",
  "bl1-acid-crawl": "233da650c0933bbeecbe02fcb261952df7c5b0eacec7dce3734fd2dabdd65903",
  "bl1-sub-anchor": "20e60f8f4709591f6f737d83f2fc669681e1c2d2d9ae53716c017ec7c5ae9b5f",
  "bl1-neon-arp": "8006b43373292f126437ce18bd53a6840718b97217ea8f489532f425f763e295",
  "bl1-house-loop": "2e0d077768faed33fc5920b9a63c1afec4bce7fb19174ecfb36590969b54b922",
  "bl1-lofi-skip": "8bf0f3c311979d6cb6be39258144c25e54afd155ea6dae2297ec9d0e0a691590",
  "bl1-cinema-hold": "1867400fa3b9928c16401a76a7e9394baeeeee4ed64adbe899ed11d97a79b29f",
  "bl1-slide-wire": "6ed2392210397ec49fbf6669cbfce9616a593e88e98f803f973cdccfb27e4509",
  "bl1-minimal-pulse": "7a321ea5d7720fcaf65e2070bc7af8994abada4373b44bf4695f8309570e24b9",
  "wt1-glass-hook": "3839c691673a6e43a59a304d42557e7250755ce2b0a55c46d2e1da3adb93ee90",
  "wt1-air-chord": "57719d1e16a7dea66b7dfeb1ab31a617e27cd42f5ce81be7053a7c3a8ae078bd",
  "wt1-pad-pulse": "c859fd663d9a81a6883c4a90a905724aed83443d11afd95c68c47432c6830d39",
  "wt1-lumen-arp": "a5f43de94b0e2d4f38cc55be5d2b6b917d3b38d0373d7376c6c695f61c130dce",
  "wt1-fog-lead": "c1ae65b57bb8caac6a5b64805dec6c5cb8e400b0c6b35969e0db850044395fa9",
  "wt1-counter-light": "b89a3f0aacfded571b151abcccbc980d21099717ab4f663f20217d6978d8a098",
  "wt1-cinema-texture": "d783beaaf9b246ab7f7d1c234a2e83a61c9ccaf3cabc68454874d9a1d65065e9",
  "wt1-signal-rise": "74247214e7b70401928ba5252c4e4553983e78a38d4332dd7c88815b39872fae",
  "dr1-dusty-amen": "8c51ac3b254bd9edfbdcf7fc93373cb6eb982f52d7035fe5aa8a6f2a2c9e80ca",
  "dr1-ghost-shuffle": "f15a786247a0efeebdb28e9a9f76a4d59db1035f96fa544cd0a6e1af67584012",
  "dr1-iron-quarters": "af9562b471e6fcf1e36823f36ae6934e5431de0582a25bdfcfb2de0c0b11628c",
  "dr1-dub-chambers": "ee20e224fd8b881f5d313bb720c1df8b979a979a019a667642da2ccf96b72ef4",
  "dr1-velvet-jack": "e7b1a9ea9d2217dd269b4406c484048ed358c20cb2d12d1072c9c351b08d91e0",
  "dr1-sunrise-hats": "35f2e61952f700ff5fae7f85c4f4f2e43e39b354b065f40662797c765ce7c699",
  "dr1-chrome-sync": "f852e5eed3df95e9055dd6ba97f34fe9ae42c5c84b0559ec0833678769ea632f",
  "dr1-machine-funk": "302309a7b139fb6b8b0996d28588de93912700b102850f16c36b27b1ca4ecda4",
  "dr1-squelch-frame": "12f182cc8ffdb2e985e2d374787c8998945897307dd3f762c57cabc7b8c70e56",
  "dr1-distant-ticks": "b065a0afaa80e36ab64afcbe3ba23f814b1f8d53d002d96f5206101fe496734c",
  "dr1-tape-swing": "18341437ad8bc8ed0e921e413996be5a9d6ef289f879b88d06abedae71e30c38",
  "dr1-titan-march": "ddc538d89e6ddd8bf717bbf9905c4e24ca877331b5a197405d44ad8f73c4165c",
  "dr1-broken-clock": "1fad61b7376daf28e250cc1e86153394b3ece831b031f2415ae0c229d11510f2",
  "dr1-jungle-sparks": "85da09d3c17837495fabfaaf277abd7c8a1d7973b452ce1502bfadfb77038c74",
  "dr1-garage-skip": "03e642221a9427c5f832861de7b9b814290a5a6ae1b7cde2ba629934022fb52c",
  "dr1-warehouse-fill": "8ad187470cb44c6c745c52e8de10dfa499975e1905c9ed4e87ba1818865596bd",
  "dr1-pulse-dust": "807b4252638b950448da39331c5c9da07d527e284814f6484fc26211520b7518",
  "dr1-ritual-toms": "369043e4aa800080ee8d2906f7d1c7baa76262d7d2cfa71fff8a712b115c66f0",
  "dr1-binary-rain": "2331b9998c89021ee0eee854b51f50c225a820c47039374d208fc8faad30e175",
  "dr1-bedroom-knock": "907796c2c5321d1314d975e1e438c4106b5b83d5212ae73e6ce5eff1bd439c85",
  "dr1-corrosive-build": "bcd1d2f900f69f1e62d5c3dcac5c1b79c609cd187c1f7240142281dd2feb8c3b",
  "dr1-robot-fill": "cd790418bf8cb99a279f55d6e0a8642d1f38992bd48f54742ff14b6890993d05",
  "dr1-halftime-crush": "c1f416d2e3f24dd56f7cbfdc938793c1a680f024022da1150a5748c4cb2d8aaa",
  "dr1-disco-lift": "8d92d46731d17d3c7cf488f6191ecd267a6fcdfe9e75306f5685130ccc295f5f",
  "bl1-redline-acid": "d830389a5ae528bbcb9232b3aef327d4b16f4b80a20975ee6bd95a509f9ddc4c",
  "bl1-rubber-dub": "63a92e42ddbc9fe4be62e1fff154c58a561530bdb7c0f9a7ab1697a68349723e",
  "bl1-basement-sequence": "d34f8d389036c60018c54e79cafd185cbc2e011c6f36cd5436f761e33697299c",
  "bl1-deep-root": "ee03f12c80216a04238df3e0e048a6341a4e3fb0d6121369789434d3b8af2e10",
  "bl1-voltage-hop": "2e597c888c4cbeee0a8a5cfb0b16b2494ebdd12a468a506646f508bdb6efeb94",
  "bl1-rewind-bass": "028a212af63530a1a360679b5d5ee5e2947f50317ee374200038db03acd337ba",
  "bl1-tide-drone": "7c9d7846eeca4dc4315785b5f04f6098127bc509065a7d1d4c26461669545c61",
  "bl1-cassette-sub": "b0b1fd58054938f91faf2f1fe4887f07043ad9b886af5238a9dde3fd6a2ed661",
  "bl1-dread-pedal": "f2d27cf3e66ac2f9b271874afe964909b1c306fa90c663ff88738afd9076f24c",
  "bl1-wrong-turn": "6c9684bc4094d2d756900627752a3704878476d1f5a61fb847c8f92eb3c57fc6",
  "bl1-acid-ascent": "a8ab3efb01f75822c6030850446b87be0107c3b0b643c6c9e6248fb8c2c9227c",
  "bl1-turnaround-fill": "fe78e42116bdde5b4ee8f94de2ff6bc1c9c2b03da8a754e5349561805c06bc01",
  "wt1-prism-lead": "9376cf88db448a5af061afc8712e7f20b8459811deedb2c3ed6808b32bcb741e",
  "wt1-sodium-chords": "14af4a744a8e1ee12252f95cfb32714a1e8c0ea12de1d58fcf5454dcd4fb7982",
  "wt1-arcade-hero": "d734d2cb54dbe4a05c689ed6e99fe05d4fbd31992c38116c99c22dc9a664cb1c",
  "wt1-rain-counter": "f07a952181b568ea361fae02f0189eb47f5ed1e0eddee2201c0ebc9e6297c16c",
  "wt1-horizon-pad": "fae0c363cfcc878f6ce372f76409bd1fc48c4d13e71fa7196b9145273bb594b6",
  "wt1-tape-memory": "3af5e8f3b2f3c1d3759c54a704a7837634a5beb35375466d4b9b4c87eb4a8b97",
  "wt1-black-signal": "13825fd1e5bbf671c30f5527629194b8e35e3f9320ae3796d24f73ec1199ae36",
  "wt1-shard-cloud": "bde4361007d065f54d63eac9c665d310527a7debe5d305415830daaae873155e",
  "wt1-acid-answer": "69e4e2e17232310373042664fb640a25ca4703ec08a7971cda8d6660d1396ada",
  "wt1-aurora-rise": "ae1c9091e000ae7e74391f896c971bcc1925792c8bf26590a6f376367052696c",
  "wt1-subway-bass": "9ac684f91eb2f6b06755ed383049ca00d88b8411d4303cfe15f782a4a03d9767",
  "wt1-doorway-transition": "ccae1ebb163ce6fd3fef30a3e2be92285b67ac8b2a2c5f6ccbf7cdd87a856ada"
} as const;
